const { test } = require('@playwright/test');
const discoveryPage = require('../helpers/Discovery-page.js');
const analysisPage = require('../helpers/Analysis-page.js');
const analysis1 = require('../helpers/thematics/covid-19/analysis/analysis1.js');
const menuSection = require('../helpers/Menu-section.js');


test.use({headless: true});
test('Test on Analysis view of COVID-19 thematic', async ({page}) => {
    await discoveryPage.goToHomePage(page);
    await discoveryPage.clickCard(page,'COVID-19');
    await menuSection.openMenu(page);
    await menuSection.goToAnalysis(page);
    await analysis1.validateTitle(page);
    await analysis1.scrollToMap(page);
    await analysis1.zoomMap(page);
    await analysis1.swipeToRight(page);
    await analysis1.swipeDown(page);
    await analysis1.surroundUruguay(page);
    await analysisPage.selectDate(page,'01012016','01012020');
    await analysisPage.clickDatasets(page,'No2');
    await analysisPage.clickDatasets(page,'No2 (Diff)');
    await analysisPage.clickGenerateBtn(page);
    await analysisPage.takeOrCompareScreenshot(page,'UpperMapResults.png');
    await analysisPage.scrollToGraphics(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'DefaultGraphicsSection.png');
    await analysisPage.openViewMenu(page);
    await analysisPage.toggleGraphicLines(page,['Min','Average','Max','St Deviation']);
    await analysisPage.toggleGraphicLines(page,['Min']);
    await analysisPage.closeViewMenu(page);
    await analysisPage.scrollToGraphics(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'GraphicsMinOnly.png');
    await analysisPage.openViewMenu(page);
    await analysisPage.toggleGraphicLines(page,['Min','Average']);
    await analysisPage.closeViewMenu(page);
    await analysisPage.scrollToGraphics(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'GraphicsAverageOnly.png');
    await analysisPage.openViewMenu(page);
    await analysisPage.toggleGraphicLines(page,['Average','Max']);
    await analysisPage.closeViewMenu(page);
    await analysisPage.scrollToGraphics(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'GraphicsMaxOnly.png');
    await analysisPage.openViewMenu(page);
    await analysisPage.toggleGraphicLines(page,['Max','St Deviation']);
    await analysisPage.closeViewMenu(page);
    await analysisPage.scrollToGraphics(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'GraphicsDeviationOnly.png');
    await analysisPage.modifyGraphicsSlider(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'LeftPieceOfGraphic.png');
    await analysisPage.moveGraphicsSlider(page);
    await analysisPage.showGraphicsLineData(page);
    await analysisPage.takeOrCompareScreenshot(page,'RightPieceOfGraphic.png');

});